const $ = id => document.getElementById(id); const money = n => '$' + Number(n || 0).toLocaleString('en-US');
async function boot() { try { const me = await api('/auth/me'); if (me.data.user.role !== 'admin') throw Error('Admin access required'); showApp(); } catch { showLogin(); } }
function showLogin() { $('login').hidden = false; $('app').hidden = true; $('adminNav').hidden = true } function showApp() { $('login').hidden = true; $('app').hidden = false; $('adminNav').hidden = false; load() }
$('loginForm').addEventListener('submit', async e => { e.preventDefault(); $('loginError').textContent = ''; try { const j = await api('/auth/admin/login', { method: 'POST', body: JSON.stringify({ email: $('email').value.trim(), password: $('password').value }) }); if (j.data.user.role !== 'admin') throw Error('Tài khoản không phải admin'); showApp() } catch (e) { $('loginError').textContent = e.message } });
$('logoutBtn')?.addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }).catch(() => { }); location.href = '/admin.html' });
async function load() { try { const [s, p, o, u, c] = await Promise.all([api('/dashboard/stats'), api('/products'), api('/orders'), api('/users'), api('/categories')]); const x = s.data; $('products').textContent = x.products; $('customers').textContent = x.customers; $('orders').textContent = x.orders; $('revenue').textContent = money(x.revenue); window.adminProducts = p.data; window.adminCategories = c.data; renderProducts(); renderOrders(o.data); renderUsers(u.data); $('pCategory').innerHTML = window.adminCategories.map(v => `<option value="${v._id}">${v.name}</option>`).join(''); } catch (e) { alert(e.message); if (/Authentication|Admin/.test(e.message)) showLogin() } }
function renderProducts() { $('productRows').innerHTML = (window.adminProducts || []).map(v => `<tr><td><img class="thumb" src="${v.image || '/favicon.svg'}" alt=""></td><td><b>${esc(v.name)}</b></td><td>${esc(v.brand)}</td><td>${money(v.salePrice ?? v.price)}</td><td>${v.stock}</td><td><span class="status ${v.isActive ? 'active' : 'locked'}">${v.isActive ? 'Active' : 'Hidden'}</span></td><td><div class="actions-inline"><button class="btn edit" data-edit="${v._id}">Sửa</button><button class="btn danger" data-delete="${v._id}">Xóa</button></div></td></tr>`).join('') || '<tr><td colspan="7">Chưa có sản phẩm.</td></tr>'; document.querySelectorAll('[data-edit]').forEach(b => b.addEventListener('click', () => openEdit(b.dataset.edit))); document.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => deleteProduct(b.dataset.delete))); }
function renderOrders(rows) { $('orderRows').innerHTML = rows.map(v => `<tr><td><b>${esc(v.user?.fullname || 'Khách')}</b><br><small>${esc(v.user?.email || '')}</small></td><td>${v.items.map(i => `${esc(i.name)} × ${i.quantity}`).join('<br>')}</td><td>${money(v.total)}</td><td>${new Date(v.createdAt).toLocaleDateString('vi-VN')}</td><td><select data-status="${v._id}">${['pending', 'confirmed', 'shipping', 'completed', 'cancelled'].map(s => `<option value="${s}" ${s === v.status ? 'selected' : ''}>${s}</option>`).join('')}</select></td></tr>`).join('') || '<tr><td colspan="5">Chưa có đơn hàng.</td></tr>'; document.querySelectorAll('[data-status]').forEach(s => s.addEventListener('change', async () => { try { await api('/orders/' + s.dataset.status + '/status', { method: 'PATCH', body: JSON.stringify({ status: s.value }) }); load() } catch (e) { alert(e.message) } })); }
function renderUsers(rows) { $('userRows').innerHTML = rows.map(v => `<tr><td>${esc(v.fullname)}</td><td>${esc(v.email)}</td><td>${esc(v.phone || '-')}</td><td><span class="status ${v.isActive ? 'active' : 'locked'}">${v.isActive ? 'Active' : 'Locked'}</span></td><td><button class="btn edit" data-user="${v._id}">${v.isActive ? 'Khóa' : 'Mở khóa'}</button></td></tr>`).join('') || '<tr><td colspan="5">Chưa có khách hàng.</td></tr>'; document.querySelectorAll('[data-user]').forEach(b => b.addEventListener('click', async () => { try { await api('/users/' + b.dataset.user + '/toggle', { method: 'PATCH' }); load() } catch (e) { alert(e.message) } })); }
function openCreate() { $('productForm').reset(); $('productId').value = ''; $('productModalTitle').textContent = 'Thêm sản phẩm'; $('productModal').classList.add('open') }
function openEdit(id) { const p = window.adminProducts.find(x => x._id === id); if (!p) return; $('productId').value = p._id; $('pName').value = p.name; $('pBrand').value = p.brand || ''; $('pCategory').value = p.category?._id || p.category || ''; $('pPrice').value = p.price; $('pSalePrice').value = p.salePrice ?? ''; $('pStock').value = p.stock; $('pImage').value = p.image || ''; $('pDescription').value = p.description || ''; $('productModalTitle').textContent = 'Sửa sản phẩm'; $('productModal').classList.add('open') }
$('addProductBtn').addEventListener('click', openCreate); document.querySelectorAll('[data-close]').forEach(b => b.addEventListener('click', () => $(b.dataset.close).classList.remove('open')));
$('productForm').addEventListener('submit', async e => { e.preventDefault(); const id = $('productId').value; const body = { name: $('pName').value.trim(), brand: $('pBrand').value.trim(), category: $('pCategory').value, price: Number($('pPrice').value), salePrice: $('pSalePrice').value === '' ? null : Number($('pSalePrice').value), stock: Number($('pStock').value), image: $('pImage').value.trim(), description: $('pDescription').value.trim(), isActive: true }; try { await api(id ? '/products/' + id : '/products', { method: id ? 'PUT' : 'POST', body: JSON.stringify(body) }); $('productModal').classList.remove('open'); await load(); } catch (e) { alert(e.message) } });
async function deleteProduct(id) { const p = window.adminProducts.find(x => x._id === id); if (!confirm(`Xóa sản phẩm "${p?.name || ''}"?`)) return; try { await api('/products/' + id, { method: 'DELETE' }); await load(); } catch (e) { alert(e.message) } }
function esc(s) { return String(s ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])) } boot();
